name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 19 * * 6'  # At 19:00 (7 PM) UTC on Saturday
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Generate .env.qa file from GitHub secrets
      run: |
        echo "BASE_URL=${{ secrets.EMAIL_PASS }}" >> .env.qa
        echo "ACCESS_TOKEN=${{ secrets.SLACKCHANNELID }}" >> .env.qa
        echo "USERNAME=${{ secrets.SLACKTOKEN }}" >> .env.qa
      shell: bash
    - name: Decode service-account.json
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT }}" | base64 --decode > service-account.json
    - name: Run Playwright tests
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: cucumber-report
        path: reports/report
        retention-days: 30
